# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A random walk Metropolis sampler  using Rcpp
#' @description a random walk Metropolis sampler  using Rcpp
#' @param sigma the standerror of norm distribution
#' @param N the number of samples
#' @return sample a random sample of size N
#' @return reject the number of rejections
#' @examples
#' \dontrun{
#' Metr(1,100)
#' }
#' @export
Metr <- function(sigma, N) {
    .Call(`_SC19015_Metr`, sigma, N)
}

